/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import clases.Comida;
import clases.Helper;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author jaime
 */
public class Acompañamientos extends javax.swing.JDialog {

    /**
     * Creates new form Acompañamientos
     */
    String ruta;
    ObjectOutputStream salida;
    ArrayList<Comida> comidas;
    int contA1 = 0;
    int contA2 = 0;
    int contA3 = 0;

    public Acompañamientos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        ruta = "src/datos/Comidas.txt";
        try {
            comidas = Helper.traerDatos(ruta);
            salida = new ObjectOutputStream(new FileOutputStream(ruta));
        } catch (IOException ex) {
            System.out.println(ex.getMessage());
        }
        Helper.volcado(salida, comidas);
        Helper.llenarTabla(tblTablaH, ruta);
        cmdEliminar.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cmdA1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblTablaH = new javax.swing.JTable();
        cmdEliminar = new javax.swing.JButton();
        cmdRegresar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        cmdA2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        cmdA3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("ACOMPAÑAMIENTOS");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, 270, 30));

        cmdA1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/papas.jpg"))); // NOI18N
        cmdA1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        cmdA1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdA1ActionPerformed(evt);
            }
        });
        jPanel1.add(cmdA1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 190, 150));

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 22)); // NOI18N
        jLabel3.setText("PAPAS FRITAS");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 170, 20));

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Lista Total"));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblTablaH.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No.", "Nombre", "Precio", "Cantidad", "Categoria"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblTablaH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTablaHMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblTablaH);

        jPanel5.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 520, 190));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 540, 220));

        cmdEliminar.setFont(new java.awt.Font("Tahoma", 3, 22)); // NOI18N
        cmdEliminar.setText("ELIMINAR");
        cmdEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(cmdEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 370, 180, 40));

        cmdRegresar.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        cmdRegresar.setForeground(new java.awt.Color(255, 0, 0));
        cmdRegresar.setText("REGRESAR");
        cmdRegresar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 3, true));
        cmdRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdRegresarActionPerformed(evt);
            }
        });
        jPanel1.add(cmdRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 440, 180, 40));

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 22)); // NOI18N
        jLabel2.setText("ENSALADA");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 90, 130, 20));

        cmdA2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ensalada.jpg"))); // NOI18N
        cmdA2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        cmdA2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdA2ActionPerformed(evt);
            }
        });
        jPanel1.add(cmdA2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 120, 190, 150));

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 22)); // NOI18N
        jLabel4.setText("McFLURRY  (Postre)");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 90, 250, -1));

        cmdA3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mcflurry.jpg"))); // NOI18N
        cmdA3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        cmdA3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdA3ActionPerformed(evt);
            }
        });
        jPanel1.add(cmdA3, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 120, 200, 150));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/McDonald's_Golden_Arches.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 500, 470));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 833, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(843, 588));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cmdA1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdA1ActionPerformed
        contA1++;
        String nombre = "PAPAS FRITAS";

        Comida p = new Comida(nombre, 4000, "Acompañamientos");

        try {
            p.guardar(salida);
        } catch (IOException ex) {
            Logger.getLogger(Acompañamientos.class.getName()).log(Level.SEVERE, null, ex);
        }
        Helper.llenarTabla(tblTablaH, ruta);
    }//GEN-LAST:event_cmdA1ActionPerformed

    private void tblTablaHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTablaHMouseClicked
        int i;
        Comida c;
        ArrayList<Comida> comidas = Helper.traerDatos(ruta);
        i = tblTablaH.getSelectedRow();

        c = comidas.get(i);

        cmdEliminar.setEnabled(true);
    }//GEN-LAST:event_tblTablaHMouseClicked

    private void cmdEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdEliminarActionPerformed
        int i, op;

        ArrayList<Comida> comidas = Helper.traerDatos(ruta);
        i = tblTablaH.getSelectedRow();
        comidas.remove(i);

        try {
            salida = new ObjectOutputStream(new FileOutputStream(ruta));
        } catch (IOException ex) {
            Logger.getLogger(Acompañamientos.class.getName()).log(Level.SEVERE, null, ex);
        }

        Helper.volcado(salida, comidas);
        Helper.llenarTabla(tblTablaH, ruta);
        cmdEliminar.setEnabled(false);
    }//GEN-LAST:event_cmdEliminarActionPerformed

    private void cmdRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdRegresarActionPerformed

        this.setVisible(false);
    }//GEN-LAST:event_cmdRegresarActionPerformed

    private void cmdA2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdA2ActionPerformed
        contA2++;
        String nombre = "ENSALADA";

        Comida p = new Comida(nombre, 4000, "Acompañamientos");

        try {
            p.guardar(salida);
        } catch (IOException ex) {
            Logger.getLogger(Acompañamientos.class.getName()).log(Level.SEVERE, null, ex);
        }
        Helper.llenarTabla(tblTablaH, ruta);
    }//GEN-LAST:event_cmdA2ActionPerformed

    private void cmdA3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdA3ActionPerformed
        contA3++;
        String nombre = "McFLURRY OREO";

        Comida p = new Comida(nombre, 3000, "Acompañamientos");

        try {
            p.guardar(salida);
        } catch (IOException ex) {
            Logger.getLogger(Acompañamientos.class.getName()).log(Level.SEVERE, null, ex);
        }
        Helper.llenarTabla(tblTablaH, ruta);
    }//GEN-LAST:event_cmdA3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Acompañamientos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Acompañamientos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Acompañamientos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Acompañamientos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Acompañamientos dialog = new Acompañamientos(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdA1;
    private javax.swing.JButton cmdA2;
    private javax.swing.JButton cmdA3;
    private javax.swing.JButton cmdEliminar;
    private javax.swing.JButton cmdRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblTablaH;
    // End of variables declaration//GEN-END:variables
}
